-- 为 amazon_fba_inventory 表字段添加中文备注
ALTER TABLE `amazon_fba_inventory` 
MODIFY COLUMN `snapshot_date` DATE DEFAULT NULL COMMENT '库存快照日期',
MODIFY COLUMN `seller_sku` VARCHAR(100) NOT NULL COMMENT '卖家SKU',
MODIFY COLUMN `item_name` TEXT COMMENT '商品名称/标题',
MODIFY COLUMN `asin` VARCHAR(20) COMMENT 'ASIN',
MODIFY COLUMN `condition_type` VARCHAR(50) DEFAULT NULL COMMENT '商品状况 (如 New)',
MODIFY COLUMN `fnsku` VARCHAR(100) COMMENT 'FNSKU',
MODIFY COLUMN `available_quantity` INT DEFAULT 0 COMMENT '可售库存数量',
MODIFY COLUMN `unavailable_quantity` INT DEFAULT 0 COMMENT '不可售库存数量',
MODIFY COLUMN `inbound_quantity` INT DEFAULT 0 COMMENT '入库总数',
MODIFY COLUMN `inbound_working` INT DEFAULT 0 COMMENT '入库处理中',
MODIFY COLUMN `shipped_quantity` INT DEFAULT 0 COMMENT '已发货在途',
MODIFY COLUMN `received_quantity` INT DEFAULT 0 COMMENT '已接收数量',
MODIFY COLUMN `total_reserved_quantity` INT DEFAULT 0 COMMENT '总预留数量',
MODIFY COLUMN `unfulfillable_quantity` INT DEFAULT 0 COMMENT '无法配送数量',
MODIFY COLUMN `sales_last_7_days` INT DEFAULT 0 COMMENT '近7天销量',
MODIFY COLUMN `sales_last_30_days` INT DEFAULT 0 COMMENT '近30天销量',
MODIFY COLUMN `days_of_supply` INT COMMENT '库存可供天数',
MODIFY COLUMN `marketplace` VARCHAR(50) COMMENT '站点 (如 US)',
MODIFY COLUMN `fba_minimum_inventory_level` DECIMAL(10, 2) DEFAULT NULL COMMENT 'FBA最低库存水平',
MODIFY COLUMN `fba_inventory_level_health_status` VARCHAR(100) DEFAULT NULL COMMENT 'FBA库存健康状态',
MODIFY COLUMN `recommended_ship_in_quantity` INT DEFAULT NULL COMMENT '建议补货量',
MODIFY COLUMN `recommended_ship_in_date` DATE DEFAULT NULL COMMENT '建议发货日期',
MODIFY COLUMN `inventory_supply_at_fba` INT DEFAULT NULL COMMENT 'FBA现有库存供应量',
MODIFY COLUMN `reserved_fc_transfer` INT DEFAULT 0 COMMENT '预留-调仓中',
MODIFY COLUMN `reserved_fc_processing` INT DEFAULT 0 COMMENT '预留-仓库处理中',
MODIFY COLUMN `reserved_customer_order` INT DEFAULT 0 COMMENT '预留-买家订单',
MODIFY COLUMN `amazon_suggestion` TEXT COMMENT '亚马逊建议',
MODIFY COLUMN `suggested_replenishment` INT COMMENT '建议补货数量',
MODIFY COLUMN `upload_batch` VARCHAR(50) COMMENT '上传批次号',
MODIFY COLUMN `upload_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
MODIFY COLUMN `shop_id` INT COMMENT '关联店铺ID';
