-- 物流跟踪表
CREATE TABLE IF NOT EXISTS `logistics_tracking` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `shop_id` INT COMMENT '关联店铺ID',
  `fba_warehouse_number` VARCHAR(100) COMMENT 'FBA入仓号',
  `tracking_number` VARCHAR(200) COMMENT '物流单号',
  `destination_country` VARCHAR(100) COMMENT '目的国家',
  `ship_date` DATE COMMENT '发货日期',
  `eta` DATETIME COMMENT '预计到达时间 (ETA)',
  `etd` DATETIME COMMENT '发船时间 (ETD)',
  `pickup_time` DATETIME COMMENT '提柜时间',
  `delivery_time` DATETIME COMMENT '派送时间',
  `fba_start_receive_time` DATETIME COMMENT 'FBA开始接收时间',
  `forwarder_name` VARCHAR(200) COMMENT '货代名称',
  `carton_count` INT COMMENT '箱数',
  `shipping_method` VARCHAR(50) COMMENT '运输方式 (海运/空运/快递)',
  `price` DECIMAL(12, 2) COMMENT '总价格',
  `price_per_carton` DECIMAL(10, 2) COMMENT '箱均价格',
  `vat_amount` DECIMAL(12, 2) COMMENT 'VAT税费缴纳金额',
  `tax_rebate` DECIMAL(12, 2) COMMENT '退税金额',
  `freight_cost` DECIMAL(12, 2) COMMENT '运费',
  `sku_list` TEXT COMMENT 'SKU列表 (JSON格式)',
  `logistics_status` ENUM('pending', 'shipped', 'in_transit', 'arrived', 'customs_cleared', 'delivered') DEFAULT 'pending' COMMENT '物流状态',
  `remarks` TEXT COMMENT '备注',
  `upload_batch` VARCHAR(50) COMMENT '上传批次',
  `upload_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_shop` (`shop_id`),
  INDEX `idx_fba_warehouse` (`fba_warehouse_number`),
  INDEX `idx_tracking_number` (`tracking_number`),
  INDEX `idx_status` (`logistics_status`),
  INDEX `idx_ship_date` (`ship_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;