-- 更新 FBA 库存表结构以支持更详细的数据
ALTER TABLE `amazon_fba_inventory`
ADD COLUMN `snapshot_date` DATE DEFAULT NULL AFTER `id`,
ADD COLUMN `condition_type` VARCHAR(50) DEFAULT NULL AFTER `asin`,
ADD COLUMN `inbound_working` INT DEFAULT 0 AFTER `inbound_quantity`,
ADD COLUMN `total_reserved_quantity` INT DEFAULT 0 AFTER `received_quantity`,
ADD COLUMN `unfulfillable_quantity` INT DEFAULT 0 AFTER `total_reserved_quantity`,
ADD COLUMN `fba_minimum_inventory_level` DECIMAL(10, 2) DEFAULT NULL AFTER `marketplace`,
ADD COLUMN `fba_inventory_level_health_status` VARCHAR(100) DEFAULT NULL AFTER `fba_minimum_inventory_level`,
ADD COLUMN `recommended_ship_in_quantity` INT DEFAULT NULL AFTER `fba_inventory_level_health_status`,
ADD COLUMN `recommended_ship_in_date` DATE DEFAULT NULL AFTER `recommended_ship_in_quantity`,
ADD COLUMN `inventory_supply_at_fba` INT DEFAULT NULL AFTER `recommended_ship_in_date`,
ADD COLUMN `reserved_fc_transfer` INT DEFAULT 0 AFTER `inventory_supply_at_fba`,
ADD COLUMN `reserved_fc_processing` INT DEFAULT 0 AFTER `reserved_fc_transfer`,
ADD COLUMN `reserved_customer_order` INT DEFAULT 0 AFTER `reserved_fc_processing`,
ADD COLUMN `your_price` DECIMAL(10, 2) DEFAULT NULL COMMENT '单价',
ADD COLUMN `sales_amount` DECIMAL(15, 2) DEFAULT 0 COMMENT '售出金额(30天)',
ADD COLUMN `pending_removal_quantity` INT DEFAULT 0 COMMENT '待删除数量',
ADD COLUMN `inv_age_0_to_90_days` INT DEFAULT 0 COMMENT '库龄0-90天',
ADD COLUMN `inv_age_91_to_180_days` INT DEFAULT 0 COMMENT '库龄91-180天',
ADD COLUMN `inv_age_181_to_270_days` INT DEFAULT 0 COMMENT '库龄181-270天',
ADD COLUMN `inv_age_271_to_365_days` INT DEFAULT 0 COMMENT '库龄271-365天',
ADD COLUMN `inv_age_366_to_455_days` INT DEFAULT 0 COMMENT '库龄366-455天',
ADD COLUMN `inv_age_456_plus_days` INT DEFAULT 0 COMMENT '库龄456天以上',
ADD COLUMN `currency` VARCHAR(10) DEFAULT 'USD' COMMENT '货币',
ADD COLUMN `units_shipped_t7` INT DEFAULT 0 COMMENT '7天发货量',
ADD COLUMN `units_shipped_t30` INT DEFAULT 0 COMMENT '30天发货量',
ADD COLUMN `units_shipped_t60` INT DEFAULT 0 COMMENT '60天发货量',
ADD COLUMN `units_shipped_t90` INT DEFAULT 0 COMMENT '90天发货量',
ADD COLUMN `alert` VARCHAR(100) DEFAULT '' COMMENT '预警状态',
ADD COLUMN `sales_price` DECIMAL(10, 2) DEFAULT NULL COMMENT '销售价格',
ADD COLUMN `lowest_price_new_plus_shipping` DECIMAL(10, 2) DEFAULT NULL COMMENT '全新最低价含运费',
ADD COLUMN `lowest_price_used` DECIMAL(10, 2) DEFAULT NULL COMMENT '二手最低价',
ADD COLUMN `recommended_action` VARCHAR(255) DEFAULT '' COMMENT '建议操作',
ADD COLUMN `deprecated_healthy_inventory_level` VARCHAR(50) DEFAULT '' COMMENT '库存健康状态(已废弃)',
ADD COLUMN `recommended_sales_price` DECIMAL(10, 2) DEFAULT NULL COMMENT '建议销售价格',
ADD COLUMN `recommended_sale_duration_days` INT DEFAULT NULL COMMENT '建议促销时长',
ADD COLUMN `estimated_cost_savings` DECIMAL(15, 2) DEFAULT 0 COMMENT '预计节省成本',
ADD COLUMN `sell_through` DECIMAL(5, 4) DEFAULT 0 COMMENT '售出率',
ADD COLUMN `item_volume` DECIMAL(15, 4) DEFAULT 0 COMMENT '商品体积',
ADD COLUMN `volume_unit_measurement` VARCHAR(20) DEFAULT '' COMMENT '体积单位',
ADD COLUMN `storage_type` VARCHAR(50) DEFAULT '' COMMENT '存储类型',
ADD COLUMN `storage_volume` DECIMAL(15, 4) DEFAULT 0 COMMENT '存储体积',
ADD COLUMN `product_group` VARCHAR(100) DEFAULT '' COMMENT '产品组',
ADD COLUMN `sales_rank` INT DEFAULT 0 COMMENT '销售排名',
ADD COLUMN `estimated_excess_quantity` INT DEFAULT 0 COMMENT '预计过剩数量',
ADD COLUMN `weeks_of_cover_t30` DECIMAL(10, 2) DEFAULT 0 COMMENT '30天覆盖周数',
ADD COLUMN `weeks_of_cover_t90` DECIMAL(10, 2) DEFAULT 0 COMMENT '90天覆盖周数',
ADD COLUMN `featuredoffer_price` DECIMAL(10, 2) DEFAULT NULL COMMENT '特色优惠价',
ADD COLUMN `sales_shipped_last_60_days` INT DEFAULT 0 COMMENT '60天销量',
ADD COLUMN `sales_shipped_last_90_days` INT DEFAULT 0 COMMENT '90天销量',
ADD COLUMN `inv_age_0_to_30_days` INT DEFAULT 0 COMMENT '库龄0-30天',
ADD COLUMN `inv_age_31_to_60_days` INT DEFAULT 0 COMMENT '库龄31-60天',
ADD COLUMN `inv_age_61_to_90_days` INT DEFAULT 0 COMMENT '库龄61-90天',
ADD COLUMN `inv_age_181_to_330_days` INT DEFAULT 0 COMMENT '库龄181-330天',
ADD COLUMN `inv_age_331_to_365_days` INT DEFAULT 0 COMMENT '库龄331-365天',
ADD COLUMN `estimated_storage_cost_next_month` DECIMAL(10, 2) DEFAULT 0 COMMENT '下月预计仓储费',
ADD COLUMN `no_sale_last_6_months` TINYINT DEFAULT 0 COMMENT '6个月无销售',
ADD COLUMN `quantity_ais_181_210_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 181-210天数量',
ADD COLUMN `estimated_ais_181_210_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 181-210天估算',
ADD COLUMN `quantity_ais_211_240_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 211-240天数量',
ADD COLUMN `estimated_ais_211_240_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 211-240天估算',
ADD COLUMN `quantity_ais_241_270_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 241-270天数量',
ADD COLUMN `estimated_ais_241_270_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 241-270天估算',
ADD COLUMN `quantity_ais_271_300_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 271-300天数量',
ADD COLUMN `estimated_ais_271_300_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 271-300天估算',
ADD COLUMN `quantity_ais_301_330_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 301-330天数量',
ADD COLUMN `estimated_ais_301_330_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 301-330天估算',
ADD COLUMN `quantity_ais_331_365_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 331-365天数量',
ADD COLUMN `estimated_ais_331_365_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 331-365天估算',
ADD COLUMN `quantity_ais_366_455_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 366-455天数量',
ADD COLUMN `estimated_ais_366_455_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 366-455天估算',
ADD COLUMN `quantity_ais_456_plus_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 456+天数量',
ADD COLUMN `estimated_ais_456_plus_days` DECIMAL(10, 2) DEFAULT 0 COMMENT 'AIS 456+天估算',
ADD COLUMN `historical_days_of_supply` INT DEFAULT 0 COMMENT '历史可供天数',
ADD COLUMN `last_updated_historical_days` DATE DEFAULT NULL COMMENT '历史可供天数最后更新',
ADD COLUMN `exempted_low_inventory_fee` TINYINT DEFAULT 0 COMMENT '是否豁免低库存费',
ADD COLUMN `low_inventory_fee_applied` TINYINT DEFAULT 0 COMMENT '本周是否收取低库存费',
ADD COLUMN `short_term_historical_days` DECIMAL(10, 2) DEFAULT 0 COMMENT '短期历史可供天数',
ADD COLUMN `long_term_historical_days` DECIMAL(10, 2) DEFAULT 0 COMMENT '长期历史可供天数',
ADD COLUMN `inventory_age_snapshot_date` DATE DEFAULT NULL COMMENT '库龄快照日期',
ADD COLUMN `total_days_supply_open_shipments` DECIMAL(10, 2) DEFAULT 0 COMMENT '含在途的总可供天数',
ADD COLUMN `supplier` VARCHAR(255) DEFAULT '' COMMENT '供应商',
ADD COLUMN `is_seasonal_next_3_months` TINYINT DEFAULT 0 COMMENT '未来3个月是否季节性',
ADD COLUMN `season_name` VARCHAR(100) DEFAULT '' COMMENT '季节名称',
ADD COLUMN `season_start_date` DATE DEFAULT NULL COMMENT '季节开始日期',
ADD COLUMN `season_end_date` DATE DEFAULT NULL COMMENT '季节结束日期';

-- 确保 seller_sku 是唯一的
-- ALTER TABLE `amazon_fba_inventory` DROP INDEX `seller_sku`;
-- ALTER TABLE `amazon_fba_inventory` ADD UNIQUE INDEX `uk_seller_sku` (`seller_sku`);
